### PR TITLE
feat: use helper mentionPost to create links

### PR DESCRIPTION
**Pull request by thlmenezes**
## Description of change

1. Refactor all anchors to docs to use mentionPost [1]
    1. mentionPost validates if post exists, this already helped to find a couple of broken links on the current docs
1. Removes draft flags from network/subnet posts
1. Creates missing post: Actions Introduction
    1. This post is mentioned in FAQ

## More info

[1] Most of the PR changes were made running the following commands

```bash
find docs -type f -exec sed -i 's/\[.*\]\((\/docs\/.*)\)/{% mentionPost "\1" %}/g' {} \;
find docs -type f -exec sed -i 's/{% mentionPost "(/{% mentionPost "/g' {} \;
find docs -type f -exec sed -i 's/)" %}/" %}/g' {} \;
```

I believe it could be made in one regex, but I could not figure it out how to remove the parenthesis from the `sed` regex

### CODE REVIEW

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #774 (feat: use helper mentionPost to create links)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #774 (feat: use helper mentionPost to create links)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

**Review by jfoliveira — APPROVED** [review]

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #774 (feat: use helper mentionPost to create links)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #774 (feat: use helper mentionPost to create links)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

**Pull request merged**
