### PR TITLE
docs: replace `pipeline_run` with `deploy`

### PR DESCRIPTION
**Pull request by thlmenezes**
## Description of change

Update required permission section with the operation deploy instead of pipeline_run

## Issues resolved by this PR

N/A

### CODE REVIEW

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #762 (docs: replace `pipeline_run` with `deploy`)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #762 (docs: replace `pipeline_run` with `deploy`)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

**Review by jfoliveira — APPROVED** [review]

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #762 (docs: replace `pipeline_run` with `deploy`)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #762 (docs: replace `pipeline_run` with `deploy`)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

**Pull request merged**
