### PR TITLE
feat: refactor previous and next links

### PR DESCRIPTION
**Pull request by thlmenezes**
## Description of change

1. Updates links.{previous, next} fields to be strings instead of arrays
    1. Attempts to use more than 1 link in these sections leads to errors
    1. In the past, using 2 or more links, caused a broken link and UI on the previous/next button
    1. Today, with the link validation on build time, it throws an error

## Issues resolved by this PR

- [x] [DVN-12727]
- [x] [DVN-12730]

## More info

Changes made using bash commands

```bash
find docs -type f -exec sed -zi 's/previous:\s\s*- /previous: /g' {} \;
find docs -type f -exec sed -zi 's/next:\s\s*- /next: /g' {} \;
```

[DVN-12727]: https://devopness.atlassian.net/browse/DVN-12727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-12730]: https://devopness.atlassian.net/browse/DVN-12730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #780 (feat: refactor previous and next links)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #780 (feat: refactor previous and next links)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #780 (feat: refactor previous and next links)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #780 (feat: refactor previous and next links)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

**Review by jfoliveira — APPROVED** [review]
LGTM!

**Pull request merged**
