### PR TITLE
docs: add required permissions information to some posts

### PR DESCRIPTION
**Pull request by thlmenezes**
## Description of change

Adds required permission information to posts from:

- Applications
- Configuration Files
- Pipelines
- Servers

## Issues resolved by this PR

- [x] [DVN-11380]
- [x] [DVN-11385]
- [x] [DVN-11386]
- [x] [DVN-11387]
- [x] [DVN-11381]
- [x] [DVN-11388]
- [x] [DVN-11389]
- [x] [DVN-11390]
- [x] [DVN-11382]
- [x] [DVN-11391]
- [x] [DVN-11392]
- [x] [DVN-11393]
- [x] [DVN-11399]
- [x] [DVN-11400]
- [x] [DVN-11383]
- [x] [DVN-11394]
- [x] [DVN-11395]
- [x] [DVN-11396]

## More info

[DVN-11380]: https://devopness.atlassian.net/browse/DVN-11380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11385]: https://devopness.atlassian.net/browse/DVN-11385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11386]: https://devopness.atlassian.net/browse/DVN-11386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11387]: https://devopness.atlassian.net/browse/DVN-11387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11381]: https://devopness.atlassian.net/browse/DVN-11381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11388]: https://devopness.atlassian.net/browse/DVN-11388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11389]: https://devopness.atlassian.net/browse/DVN-11389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11390]: https://devopness.atlassian.net/browse/DVN-11390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11382]: https://devopness.atlassian.net/browse/DVN-11382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11391]: https://devopness.atlassian.net/browse/DVN-11391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11392]: https://devopness.atlassian.net/browse/DVN-11392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11393]: https://devopness.atlassian.net/browse/DVN-11393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11399]: https://devopness.atlassian.net/browse/DVN-11399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11400]: https://devopness.atlassian.net/browse/DVN-11400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11383]: https://devopness.atlassian.net/browse/DVN-11383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11394]: https://devopness.atlassian.net/browse/DVN-11394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11395]: https://devopness.atlassian.net/browse/DVN-11395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-11396]: https://devopness.atlassian.net/browse/DVN-11396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #721 (docs: add required permissions information to some posts)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #721 (docs: add required permissions information to some posts)`: Devopness application `thlmenezes-site.devopness.com` deployment **failed** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #721 (docs: add required permissions information to some posts)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

**Review by jfoliveira — APPROVED** [review]

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #721 (docs: add required permissions information to some posts)`: Devopness application `thlmenezes-site.devopness.com` deployment **failed** on action <https://thlmenezes-site.devopness.com>

**Pull request merged**
