### PR TITLE
feat: update server remove post

### PR DESCRIPTION
**Pull request by thlmenezes**
## Description of change

Updates remove a server post to guide users removing self hosted servers, outlining the differences with deleting a devopness provisioned server on a cloud provider (e.g aws, digitalocean, gcp)

## Issues resolved by this PR

- [x] [DVN-12580]
- [x] [DVN-12581]

## More info

[DVN-12580]: https://devopness.atlassian.net/browse/DVN-12580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DVN-12581]: https://devopness.atlassian.net/browse/DVN-12581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #776 (feat: update server remove post)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #776 (feat: update server remove post)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

**Review by jfoliveira — CHANGES_REQUESTED** [review]

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #776 (feat: update server remove post)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #776 (feat: update server remove post)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

**Comment by thlmenezes** [comment]
Deployed pipeline for `PR #776 (feat: update server remove post)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

**Review by jfoliveira — APPROVED** [review]

**Pull request merged**
